import { Geist, Geist_Mono, Merriweather } from "next/font/google";
import "../styles/styles.scss";
import '../styles/styles.scss';
import Header from '../components/Header';
import Footer from '../components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin", "cyrillic"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let user = null;
  try {
    const res = await fetch('http://localhost:3000/api/user/me', { cache: 'no-store' });
    if (res.ok) {
      const data = await res.json();
      user = data.user;
    }
  } catch {}

  console.log('Layout: user =', user);

  return (
    <html lang="ru">
      <body>
        <Header initialUser={user} />
        {children}
        <Footer />
      </body>
    </html>
  );
}